# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5)
print(A)
print(A.shape) #(rader, kolumner)
print(A.ndim) # antal dimensioner/axlar, här 2-dim 
print(A.size) # antal element 
print(A.dtype) # datatype för elementen
print(A.itemsize) # antal byte per element

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
2
15
int64
8


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [24]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2 # Alt kan man köra np.full((3, 3), 2) jag tycker den är tydligare
D = B + C # elementvis +
E = B - C # elementvis -
F = B * C # elementvis *
G = B @ C # vektormultiplikation

print("B")
print(B)
print("C")
print(C)
print("Elementvis +")
print(D)
print("elementvis -")
print(E)
print("elementvis *")
print(F)
print("vektormultiplikation")
print(G)

B
[[1 2 3]
 [4 5 6]
 [7 8 9]]
C
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Elementvis +
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
elementvis -
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
elementvis *
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
vektormultiplikation
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [26]:
D = np.arange(1, 10).reshape(3, 3)
print("D")
print(D)

print("Eulers konstant upphöjt i varje element, elementvis över matrisen")
print(np.exp(D))

print("min över hela matrisen")
print(np.min(D))

print("min per rad dvs längs den horisontella axeln 1")
print(np.min(D, axis=1))

print("min per kolumn dvs längs den vertikala axeln 0")
print(np.min(D, axis=0))

print("ersätter min med argmin i 2, för index för min-värdet i hela matrisen som om den vore en platt vektor")
print(np.argmin(D))

print("index för min per rad")
print(np.argmin(D, axis=1))

print("Summan av alla element i hela matrisen")
print(np.sum(D))

print("medel per kolumn, returnerar float dvs heltal blir x.")
print(np.mean(D, axis=0))

print("median per kolumn, returnerar float dvs heltal blir x.")
print(np.median(D, axis=0))


D
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Eulers konstant upphöjt i varje element, elementvis över matrisen
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
min över hela matrisen
1
min per rad dvs längs den horisontella axeln 1
[1 4 7]
min per kolumn dvs längs den vertikala axeln 0
[1 2 3]
ersätter min med argmin i 2, för index för min-värdet i hela matrisen som om den vore en platt vektor
0
index för min per rad
[0 0 0]
Summan av alla element i hela matrisen
45
medel per kolumn, returnerar float dvs heltal blir x.
[4. 5. 6.]
median per kolumn, returnerar float dvs heltal blir x.
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [29]:
A = np.arange(1, 16).reshape(3,5)
print(A)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
print(A[1])
print(type(A[1]))

print(A[1, :]) # Eget test
print(type(A[1, :]))

print(A[[1]]) # Eget test
print(type(A[[1]]))


[ 6  7  8  9 10]
<class 'numpy.ndarray'>
[ 6  7  8  9 10]
<class 'numpy.ndarray'>
[[ 6  7  8  9 10]]
<class 'numpy.ndarray'>


**Answer:**

In [ ]:
NumPy antar att man vill ha all data från de dimensioner man utelämnat, dvs motsvarar A[1, :]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [29]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# Iteration med for. Dvs i antar värdet av elementet när matrisen itereras igenom
for i in A:
    print(i)
    

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [38]:
a = np.arange(30) # Skapar en ndarray dvs en np n-dim array
print(type(a))
b = a.reshape((2, 3, -1)) # 3D-matris, resp värde anger: 2 block/skivor, 3 rader, 
                          #-1: skapar så många kolumner som behövs för att alla element ska få plats
                          # dvs 2*3*x=30 -> x=5 som då blir antal kolumner
                          # det krävs att det går jämnt upp för att koden ska fungera
print(a)
print()
print(type(b))
print(b.ndim)
print(b)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

<class 'numpy.ndarray'>
3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [4]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1)
print(m1 + m2)

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [5]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [35]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
    def add_mult_matrice(A: np.ndarray, B: np.ndarray, C):
        allowed_op = ["add", "multiply"] # Tillåtna värden för inmatade C

        if C not in allowed_op: # Testar att C finns i allowed_op
            return (f"{C} must be one of {allowed_op}")
            
        elif C == "add": # Testar att A och B har samma shape så att matematisk addition fungerar
            if A.shape == B.shape:
                return A + B
            else:
                return "Vectors are not compatible"
            
        elif C == "multiply": # Testar att A och B har kompatibel shape så att matematisk multiplikation fungerar
            if A.shape[1] == B.shape[0]: # antalet kolumner i den första matrisen måste vara lika med antalet rader i den andra matrisen
                return A @ B
            else:
                return "Vectors are not compatible"


# Två testfall
matris_A = np.array([[1, 2, 3], [5, 6, 7]])
matris_B = np.array([[3, 4], [7, 8], [8, 9]])
print(add_mult_matrice(matris_A, matris_B, "add"))
print(add_mult_matrice(matris_A, matris_B, "multiply"))


Vectors are not compatible
[[ 41  47]
 [113 131]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [89]:
# 10.1.1

x = (4, 3)
x = np.array([[4], [3]])
print(x)
print(type(x))

# Vilken dim har x?
print(x.ndim)
print(x.shape)

# Beräkna 5x
B = 5 * x
print(B)

# Beräkna 3x
C = 3 * x
print(C)

# Beräkna 5x + 3x
D = 5 * x + 3 * x
print(D)

# Beräkna 8x
E = 8 * x
print(E)

# Beräkna 4x-x
F = 4 * x - x
print(F)

# Beräkna xT (x transponerat)
G = x.transpose()
print(G)

# Är x + xT definierat?
print("x + xT")
H = x + x.transpose()
print("H")
print(H)
print(H.shape) #(rader, kolumner)
print(H.ndim) # antal dimensioner/axlar, här 2-dim 
print(H.size) # antal element 
print(H.dtype) # datatype för elementen
print(add_mult_matrice(H, x.transpose(), "add"))

# Normen beräkas med np.linalg.norm(v)
I = np.linalg.norm(x)
print(I)



[[4]
 [3]]
<class 'numpy.ndarray'>
2
(2, 1)
[[20]
 [15]]
[[12]
 [ 9]]
[[32]
 [24]]
[[32]
 [24]]
[[12]
 [ 9]]
[[4 3]]
x + xT
H
[[8 7]
 [7 6]]
(2, 2)
2
4
int64
Vectors are not compatible
5.0


In [82]:
# 10.1.2
V = np.array([[3], [7], [0], [11]])
print(V)
# Vilken dim har V, dvs shape
A = V.shape
Adim = V.ndim
print(Adim)
print(A) # (4, 1) dvs 4 rader och 1 kolumn
Adim = V.ndim
print(Adim) # 2 dvs 2 dimensioner

# Beräkna 2v
B = 2 * V
print(B)

# Beräkna 5v+2v
C = 5 * V + 2 * V
print(C)

# Beräkna 4v-2v
D = 4 * V - 2 * V
print(D)

# Transponera v, vad blir dimensionen efteråt
E = V.transpose()
print(E)
print(E.ndim)
print(E.shape)

# Beräkan normen av v
F = np.linalg.norm(V)
print(F)


[[ 3]
 [ 7]
 [ 0]
 [11]]
2
(4, 1)
2
[[ 6]
 [14]
 [ 0]
 [22]]
[[21]
 [49]
 [ 0]
 [77]]
[[ 6]
 [14]
 [ 0]
 [22]]
[[ 3  7  0 11]]
2
(1, 4)
13.379088160259652


In [ ]:
# 10.1.3
V1 = np.array([[4], [3], [1], [5]])
V2 = np.array([[2], [3], [1], [1]])

# Beräkna normen av v1
A = np.linalg.norm(V1)
print(A)

# Beräkna normen av v1-v2 dvs |v1-v2|
B = np.linalg.norm(V1 - V2)
print(B)


7.14142842854285
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [95]:
def add_mult_sub_matrice(A: np.ndarray, B: np.ndarray, C):
        allowed_op = ["add", "multiply", "sub"]

        if C not in allowed_op:
            return (f"{C} must be one of {allowed_op}")
            
        elif C == "add":
            if A.shape == B.shape: # A and B must have same shape for add and sub
                return A + B
            else:
                return "Vectors are not compatible"
        
        elif C == "sub":
            if A.shape == B.shape: # A and B must have same shape for add and sub
                return A - B
            else:
                return "Vectors are not compatible"
                
        elif C == "multiply":
            if A.shape[1] == B.shape[0]: # number of columns in the first matrix to be equal to the number of rows in the second matrix
                return A @ B
            else:
                return "Vectors are not compatible"

matris_A = np.array([[1, 2, 3], [5, 6, 7]])
matris_B = np.array([[3, 4], [7, 8], [8, 9]])
print(add_mult_sub_matrice(matris_A, matris_B, "sub"))
print(add_mult_sub_matrice(matris_A, matris_B, "multiply"))

Vectors are not compatible
[[ 41  47]
 [113 131]]


In [120]:
# 10.2.1 
 
A = np.array([[2, 1, -1], [1, -1, 1]])
# print(f"A: \n{A}")

B = np.array([[4, -2, 1], [2, -4, -2]])
# print(f"B: \n{B}")

C = np.array([[1, 2], [2, 1]])
# print(f"C: \n{C}")

D = np.array([[3, 4], [4, 3]])
# print(f"D: \n{D}")

E = np.array([[1], [2]])
# print(f"E: \n{E}")

I = np.array([[1, 0], [0, 1]])
# print(f"I: \n{I}")

# Funktionen add_mult_sub_matrice skapad från tidigare övning, subtraktion är tillagt

#10.2.1 a: 2A
print("10.2.1 a")
a = 2 * A
print(f"2A=\n{a}\n")

#10.2.1 b: B-2A
print("10.2.1 b")
b = add_mult_sub_matrice(B, 2 * A, "sub")
print(f"B-2A=\n{b}\n")

#10.2.1 c: 3C-2E
print("10.2.1 c")
c = add_mult_sub_matrice(3 * C, 2 * E, "sub")
print(f"3C-2E\n{c}\n")

#10.2.1 d: 2D-3C
print("10.2.1 d")
d = add_mult_sub_matrice(2 * D, 3 * C, "sub")
print(f"2D-3C=\n{d}\n")

#10.2.1 e: DT+2D
print("10.2.1 e")
e = add_mult_sub_matrice(D.transpose(), 2 * D, "add")
print(f"DT+2D=\n{e}\n")

#10.2.1 f: 2CT-2DT
print("10.2.1 f")
f = add_mult_sub_matrice(2 * C.transpose(), 2 * D.transpose(), "sub")
print(f"2CT-2DT=\n{f}\n")

#10.2.1 g: AT-B
print("10.2.1 g")
g = add_mult_sub_matrice(A.transpose(), B, "sub")
print(f"AT-B=\n{g}\n")

#10.2.1 h: AC
print("10.2.1 h")
h = add_mult_sub_matrice(A, C, "multiply")
print(f"AC=\n{h}\n")

#10.2.1 i: CD
print("10.2.1 i")
i = add_mult_sub_matrice(C, C, "multiply")
print(f"CD=\n{i}\n")

#10.2.1 j: CB
print("10.2.1 j")
j = add_mult_sub_matrice(C, B, "multiply")
print(f"CB=\n{j}\n")

#10.2.1 k: CI
print("10.2.1 k")
k = add_mult_sub_matrice(C, I, "multiply")
print(f"CI=\n{k}\n")

#10.2.1 l: ABT
print("10.2.1 l")
l = add_mult_sub_matrice(a, B.transpose(), "multiply")
print(f"ABT=\n{l}\n")

10.2.1 a
2A=
[[ 4  2 -2]
 [ 2 -2  2]]

10.2.1 b
B-2A=
[[ 0 -4  3]
 [ 0 -2 -4]]

10.2.1 c
3C-2E
Vectors are not compatible

10.2.1 d
2D-3C=
[[3 2]
 [2 3]]

10.2.1 e
DT+2D=
[[ 9 12]
 [12  9]]

10.2.1 f
2CT-2DT=
[[-4 -4]
 [-4 -4]]

10.2.1 g
AT-B=
Vectors are not compatible

10.2.1 h
AC=
Vectors are not compatible

10.2.1 i
CD=
[[5 4]
 [4 5]]

10.2.1 j
CB=
[[  8 -10  -3]
 [ 10  -8   0]]

10.2.1 k
CI=
[[1 2]
 [2 1]]

10.2.1 l
ABT=
[[10  4]
 [14  8]]



In [121]:
# 10.2.2
A=np.array([[2, 3, 4], [5, 4, 1]])
AAT = add_mult_sub_matrice(A, A.transpose(), "multiply")
print(f"AAT=\n{AAT}\n")


AAT=
[[29 26]
 [26 42]]



In [128]:
#10.2.3
A=np.array([[1, 2],[2, 4]])
B=np.array([[2, 1],[1, 3]])
C=np.array([[4, 3],[0, 2]])
AB = A @ B 
AC = A @ C
print(AB == AC)
print(B == C)


[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


In [28]:
#10.2.4
# Jag ville testa denna för eget lärande. Jag tog hjälp av gemini som visade mig sympy and bollade olika utskriftsformat.
import sympy as sp

x1, x2, x3 = sp.symbols('x1 x2 x3')

AA = sp.Matrix([
    [3, 2, 4],
    [2, 3, 8],
    [4, 1, 3],
    [7, 1, 5]
])

xx = sp.Matrix([[x1], [x2], [x3]])
bb = sp.Matrix([[7], [4], [11], [9]])

# Standard-utskrift
print("Standard design:")
print(f"{AA * xx} = {bb}")

# Aktiverar snyggare matte-utseende
sp.init_printing()
print()
print("Mer matte-likt:")
display(AA * xx, "=", bb)

# Tar hjälp av ekvations-motorn sp.Eq
print("Läroboksmässig:")
display(sp.Eq(AA * xx, bb))

Standard design:
Matrix([[3*x1 + 2*x2 + 4*x3], [2*x1 + 3*x2 + 8*x3], [4*x1 + x2 + 3*x3], [7*x1 + x2 + 5*x3]]) = Matrix([[7], [4], [11], [9]])

Mer matte-likt:


⎡3⋅x₁ + 2⋅x₂ + 4⋅x₃⎤
⎢                  ⎥
⎢2⋅x₁ + 3⋅x₂ + 8⋅x₃⎥
⎢                  ⎥
⎢ 4⋅x₁ + x₂ + 3⋅x₃ ⎥
⎢                  ⎥
⎣ 7⋅x₁ + x₂ + 5⋅x₃ ⎦

'='

⎡7 ⎤
⎢  ⎥
⎢4 ⎥
⎢  ⎥
⎢11⎥
⎢  ⎥
⎣9 ⎦

Läroboksmässig:


⎡3⋅x₁ + 2⋅x₂ + 4⋅x₃⎤   ⎡7 ⎤
⎢                  ⎥   ⎢  ⎥
⎢2⋅x₁ + 3⋅x₂ + 8⋅x₃⎥   ⎢4 ⎥
⎢                  ⎥ = ⎢  ⎥
⎢ 4⋅x₁ + x₂ + 3⋅x₃ ⎥   ⎢11⎥
⎢                  ⎥   ⎢  ⎥
⎣ 7⋅x₁ + x₂ + 5⋅x₃ ⎦   ⎣9 ⎦

### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

#The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base) # "None" innebär Copy
print(v2.base) # Original.array innebär View


[0 1 2 3]
[2 3]
None
[0 1 2 3]
